services:
  - type: web
    name: youtube-audio-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main_robust.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 